# Generated by Django 3.2.7 on 2021-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('useremail', models.EmailField(default='', max_length=30)),
                ('graduation', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=14)),
                ('activityname', models.CharField(default='', max_length=14)),
                ('activityassigned', models.CharField(default=' ', max_length=30)),
            ],
        ),
    ]
